mysql:
  username: "root"
  password: "123456"
  host: "127.0.0.1"
  port: 3306
  dbname: "seckill"
  timeout: 10

rpc:
  dbservport: ":53277"
  cacheservport: ":46288"
  timeout: 5

redis:
  host: "localhost"
  port: 6379
  password: "dbw06151x"
  db: 0
  